[KAKAO]
client_id = "8e31106f3f70372239cbabeeef99fd70"
redirect_uri = "http://localhost:8501"

[CLICKSEND]
CLICKSEND_USERNAME = "dmdals1012@gmail.com"
CLICKSEND_API_KEY = "97213F88-92A4-B51A-99AF-D059267385B6"